### ISSUE TITLE
Error: Cannot find module 'node-dht-sensor'  

### ISSUE THREAD

**Issue by ghost** [fulr/node-dht22#1]
Whenever I try and run any of the test programs I get this error:
Error: Cannot find module 'node-dht-sensor'
 . I installed it via npm.

**Comment by fulr** [comment]
Can you give some more information?
I cannot reproduce it.

**Comment by ghost** [comment]
Ahh..i manage to get it to work but this is what its returning:
{ read: [Function] }
{ state: -1, humidity: 8.337801179739172e-19, temperature: 0 }

I'm using a dht22 on gpio8

**Comment by fulr** [comment]
It only works on GPIO 4. At least as far as I know. You can try though.
